service: crucible-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, ''}
    DEEPSEEK_API_KEY: ${env:DEEPSEEK_API_KEY, ''}
    DEEPSEEK_API_URL: ${env:DEEPSEEK_API_URL, 'https://api.deepseek.com/v1'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

package:
  patterns:
    - 'crucible-synthesis-config.json'
    - '../crucible-core/src/**'
    - '!../crucible-core/node_modules/**'
    - '!../crucible-core/examples/**'
    - '!../crucible-core/README.md'
    - '!../crucible-core/package-lock.json'

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    timeout: 30
    memorySize: 512

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline

custom:
  dotenv:
    path: ../.env
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    exclude:
      - aws-sdk
      - dotenv
    packager: npm
    target: node18
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true 